############################################################################################
# Julia script for plotting and animating from the data generated by GADGET2/3/4. 
############################################################################################

using GadgetIO, GadgetUnits, SPHtoGrid, SPHKernels
using Unitful, UnitfulAstro
using Plots, LaTeXStrings, StatsPlots.PlotMeasures, AverageShiftedHistograms
using Glob, FileIO, VideoIO, DelimitedFiles, Accessors

"Hₒ = 100 km s^(-1) Mpc^(-1) in Gyr^(-1)"
const HUBBLE_CONST = 0.102201

"""
Solar metallicity.

M. Asplund et al. (2009). The Chemical Composition of the Sun. Annual Review of Astronomy 
and Astrophysics, 47(1), 481–522. https://doi.org/10.1146/annurev.astro.46.060407.145222
"""
const SOLAR_METALLICITY = 0.0134

include("auxiliary.jl")
include("data_acquisition.jl")
include("plotting.jl")
include("pipelines.jl")