name: Deploy documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jlenv: 'docs/'
            makejl: 'docs/make.jl'
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - run: |
          julia --project=${{ matrix.jlenv }} -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=${{ matrix.jlenv }} --color=yes ${{ matrix.makejl }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
