name: Run CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1',]
        julia-arch: [x64, x86]
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.6.1
        with:
          version: ${{ matrix.julia-version }}
      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@v1.7
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: lcov.info
